### ISSUE TITLE
Protect API keys by keeping them outside of GIT.

### ISSUE THREAD

**Issue by quicken** [uq-seven-up/neverland#6]
Currently, the API keys for accessing the weather API are hardcoded and a part of source control.

This is not a good practice as other people could easily access and abuse those API keys. While it is not really too much of an issue for a weather API. It would be an issue if these API keys were needed to talk to an e-commerce application. As such we should follow best practice and keep API keys outside of source control. 

This issue is completed when API keys are set using environment variables. An example of using environment variables is the mechanism used to configure access to mongo DB.

**Comment by srobayo11** [comment]
task done
